site_name: jobspy2
repo_url: https://github.com/franciscomoretti/jobspy2
site_url: https://franciscomoretti.github.io/jobspy2
site_description: Scrape job posting from different job boards
site_author: Francisco Moretti
edit_uri: edit/main/docs/
repo_name: franciscomoretti/jobspy2
copyright: Maintained by <a href="https://franciscomoretti.com">franciscomoretti</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/jobspy2"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/franciscomoretti/jobspy2
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/jobspy2

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
